### ISSUE TITLE
MissingDimensionsError when using combined_preprocessing

### ISSUE THREAD

**Issue by DaisyShi19** [jbusecke/cmip6_preprocessing#12] opened 2020-02-27 22:40 UTC
![Screen Shot 2020-02-27 at 1 28 14 PM](https://user-images.githubusercontent.com/56416963/75493370-920fb900-596e-11ea-833c-b4e2b3b0d26e.png)

Hi, there, 

Thanks for sharing the preprocessing tools for cmip6! I am trying to use it on the monthly SST data from model pi-control runs. However, it keeps giving me error (attached screen shot). There are in total 44 models. 

Thanks!
Daisy

**Comment by jbusecke** [comment] 2020-02-27 22:58
Thanks for using cmip6_preprocessing!

Could you paste the full error message here? Were any warnings shown?

I suspect that this is a 'new' model (e.g. it wasnt available on the pangeo cloud when I wrote this package. 

Can you try this with single models to see if this is specific to a particular one?

**Comment by jbusecke** [comment] 2020-02-28 15:01
It seems like there are several models that are not encoded in the module (GISS-E2-G,ESSM-1-1, ACCESS-CM2, CESM-FV2, CESM-WACCM-FV2, FIO-ESM-2-0, ACCESS-ESM1-5). I assume that these are atmospheric models? I have not extensively worked with atmospheric output, mostly with ocean. 

Quick fix: Try to exclude these models in your search, and let me know if that works.

Ill see if I get some time to add the necessary entries to the module.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jbusecke** [comment] 2020-02-28 15:07
@naomi-henderson are new models still coming into the cloud bucket? or do we now have at least “one of everything?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by naomi-henderson** [comment] 2020-02-28 15:22
Yes, we are constantly updating the cloud bucket. Moreover LLNL-ESGF is still adding new models - there are currently 84 available (over all activities and experiments) and we have 69 in our cloud collection:
```
['ACCESS-CM2', 'ACCESS-ESM1-5', 'AWI-CM-1-1-MR', 'BCC-CSM2-MR', 'BCC-ESM1', 'CAMS-CSM1-0', 'CESM1-1-CAM5-CMIP5', 'CESM2', 'CESM2-FV2', 'CESM2-WACCM', 'CESM2-WACCM-FV2', 'CIESM', 'CMCC-CM2-HR4', 'CMCC-CM2-VHR4', 'CNRM-CM6-1', 'CNRM-CM6-1-HR', 'CNRM-ESM2-1', 'CanESM5', 'CanESM5-CanOE', 'E3SM-1-0', 'E3SM-1-1', 'E3SM-1-1-ECA', 'EC-Earth3', 'EC-Earth3-LR', 'EC-Earth3-Veg', 'ECMWF-IFS-HR', 'ECMWF-IFS-LR', 'FGOALS-f3-L', 'FGOALS-g3', 'FIO-ESM-2-0', 'GFDL-AM4', 'GFDL-CM4', 'GFDL-CM4C192', 'GFDL-ESM4', 'GFDL-OM4p5B', 'GISS-E2-1-G', 'GISS-E2-1-G-CC', 'GISS-E2-1-H', 'GISS-E2-2-G', 'HadGEM3-GC31-HM', 'HadGEM3-GC31-LL', 'HadGEM3-GC31-LM', 'HadGEM3-GC31-MM', 'IITM-ESM', 'INM-CM4-8', 'INM-CM5-0', 'IPSL-CM6A-ATM-HR', 'IPSL-CM6A-LR', 'KACE-1-0-G', 'MCM-UA-1-0', 'MIROC-ES2L', 'MIROC6', 'MPI-ESM-1-2-HAM', 'MPI-ESM1-2-HR', 'MPI-ESM1-2-LR', 'MPI-ESM1-2-XR', 'MRI-AGCM3-2-H', 'MRI-AGCM3-2-S', 'MRI-ESM2-0', 'NESM3', 'NICAM16-7S', 'NICAM16-8S', 'NICAM16-9S', 'NorCPM1', 'NorESM1-F', 'NorESM2-LM', 'NorESM2-MM', 'SAM0-UNICON', 'UKESM1-0-LL']
```
Funny, of the ones you list, we don't have GISS-E2-G, though. Maybe because their node (esgf.nccs.nasa.gov) is often unavailable.

**Comment by naomi-henderson** [comment] 2020-02-28 15:27
... and 53 of our GC models have ocean data:
`['ACCESS-CM2', 'ACCESS-ESM1-5', 'AWI-CM-1-1-MR', 'BCC-CSM2-MR', 'BCC-ESM1', 'CAMS-CSM1-0', 'CESM1-1-CAM5-CMIP5', 'CESM2', 'CESM2-FV2', 'CESM2-WACCM', 'CESM2-WACCM-FV2', 'CIESM', 'CNRM-CM6-1', 'CNRM-CM6-1-HR', 'CNRM-ESM2-1', 'CanESM5', 'CanESM5-CanOE', 'E3SM-1-0', 'E3SM-1-1', 'E3SM-1-1-ECA', 'EC-Earth3', 'EC-Earth3-LR', 'EC-Earth3-Veg', 'FGOALS-f3-L', 'FIO-ESM-2-0', 'GFDL-CM4', 'GFDL-ESM4', 'GFDL-OM4p5B', 'GISS-E2-1-G', 'GISS-E2-1-G-CC', 'GISS-E2-1-H', 'GISS-E2-2-G', 'HadGEM3-GC31-LL', 'HadGEM3-GC31-MM', 'INM-CM4-8', 'INM-CM5-0', 'IPSL-CM6A-LR', 'KACE-1-0-G', 'MCM-UA-1-0', 'MIROC-ES2L', 'MIROC6', 'MPI-ESM-1-2-HAM', 'MPI-ESM1-2-HR', 'MPI-ESM1-2-LR', 'MRI-ESM2-0', 'NESM3', 'NICAM16-7S', 'NorCPM1', 'NorESM1-F', 'NorESM2-LM', 'NorESM2-MM', 'SAM0-UNICON', 'UKESM1-0-LL']`

**Comment by jbusecke** [comment] 2020-02-28 15:40
> Funny, of the ones you list, we don't have GISS-E2-G, though. Maybe because their node (esgf.nccs.nasa.gov) is often unavailable.

That is weird... @DaisyShi19 are you working with data in the cloud or on some other machine?

**Comment by naomi-henderson** [comment] 2020-02-28 15:41
Ah, you typed `GISS-E2-G`, which we don't have, but Daisy's error message specifies `GISS-E2-2-G`, which we do have in the cloud

**Comment by jbusecke** [comment] 2020-02-28 15:43
Ah, sorry I was on the train and phone. 

> Yes, we are constantly updating the cloud bucket. Moreover LLNL-ESGF is still adding new models - there are currently 84 available (over all activities and experiments) and we have 69 in our cloud collection:

@naomi-henderson is there some simple automatic way to alert me (raise an issue here at `cmip6_preprocessing`) if more models are added? Ill add the details for the new models asap, and will probably change the behavior to return the unprocessed dataset instead of erroring out.

But it would be great to have timely ping if new models are available 😁

**Comment by aaronspring** [comment] 2020-02-28 15:46
I got the same error when trying to load `MPI-ESM1-2-LR(HAM)` `Amon` output with `cmip6_preprocessing`. I guess the current module is written for ocean output. atmospheric output seems so aligned that `cmip6_preprocessing` is not so much needed

**Comment by naomi-henderson** [comment] 2020-02-28 15:50
@jbusecke , the only way I have of knowing is:
```
import pandas as pd
url = 'https://cmip6.storage.googleapis.com/cmip6-zarr-consolidated-stores.csv'
df = pd.read_csv(url)
len(df.source_id.unique())
```
oops - the answer is now 70 - so we just added a model

It is probably best if you occasionally check - I am flooded with data requests, etc and probably won't remember ...

**Comment by jbusecke** [comment] 2020-02-28 15:55
> It is probably best if you occasionally check - I am flooded with data requests, etc and probably won't remember ...

Will do. Also big thanks for doing all of this. I didnt mean to add more work.

**Comment by jbusecke** [comment] 2020-02-28 15:56
@aaronspring, yes I have been developing this ocean-centric, but I will look into the atmos variables soon.

**Comment by DaisyShi19** [comment] 2020-02-28 19:27
> It seems like there are several models that are not encoded in the module (GISS-E2-G,ESSM-1-1, ACCESS-CM2, CESM-FV2, CESM-WACCM-FV2, FIO-ESM-2-0, ACCESS-ESM1-5). I assume that these were newly added to the cloud storage and
> 
> Quick fix: Try to exclude these models in your search, and let me know if that works.
> 
> Ill see if I get some time to add the necessary entries to the module.
> 
> Sent with [GitHawk](http://githawk.com)

Thank you! Please keep me updated!

> It seems like there are several models that are not encoded in the module (GISS-E2-G,ESSM-1-1, ACCESS-CM2, CESM-FV2, CESM-WACCM-FV2, FIO-ESM-2-0, ACCESS-ESM1-5). I assume that these were newly added to the cloud storage and
> 
> Quick fix: Try to exclude these models in your search, and let me know if that works.
> 
> Ill see if I get some time to add the necessary entries to the module.
> 
> Sent with [GitHawk](http://githawk.com)

Thank you! Please keep me updated!

**Comment by jbusecke** [comment] 2020-02-29 23:11
@DaisyShi19 I just released v0.1.2, which includes every model on the pangeo cloud with ocean output. Could you update to the new version (please use pip or install from source, conda is not yet working) and let me know if the problem is solved?

@naomi-henderson I have integrated your code into the CI, so if more models are added, I am able to detect it from my end.

**Comment by jbusecke** [comment] 2020-02-29 23:45
Now also available on conda!

**Comment by DaisyShi19** [comment] 2020-03-02 18:22
Hi @jbusecke thank you for the update!
I did conda install and tried again with the same code. It still gives the same missing dimensions error about 'lon' at 18.2%. Perhaps it is still running the old version? How can I make sure it is running the new version?
Thanks!

**Comment by jbusecke** [comment] 2020-03-02 18:34
```
import cmip6_preprocessing

cmip6_preprocessing.__version__
```
should do the trick. Let me know if the problem persists.

**Comment by jbusecke** [comment] 2020-03-02 18:35
Just looked over your code and found another possible issue. If you have the newest version, can you try it with `grid_label=['gn']` only, and let me know if that works?

**Comment by jbusecke** [comment] 2020-03-04 14:22
@DaisyShi19, did any of these updates solve your problem?

**Comment by DaisyShi19** [comment] 2020-03-04 17:49
@jbusecke Yes, it worked when I use grid_label=['gn']. Thank you! I haven't got to the next step yet, will try to use xgcm shortly.

**Comment by jbusecke** [comment] 2020-03-04 18:05
If you update to the newest version, you should also be able to use the regridded `gr` files. 
To see how to get xgcm to work I recommend the second example [here](https://github.com/jbusecke/cmip6-hackathon-demos).

A warning: these might be outdated. I have been thinking about better ways to work with staggered grids and will implement them soon. Please raise another issue if you experience problems. 

If both `gn` and `gr` files work with the latest version, feel free to close the issue. Thanks

**Comment by DaisyShi19** [comment] 2020-03-04 18:30
Great! Is the newest version v0.1.2

**Comment by jbusecke** [comment] 2020-03-04 18:45
That is the latest released version! Glad it worked for you. Closing this.

**Comment by DaisyShi19** [comment] 2020-03-04 18:59
It won't work for the 'gr' still but good for now. I'll definitely see the example you recommended. Thanks a lot @jbusecke !

**Comment by jbusecke** [comment] 2020-03-04 19:06
I think you are right. The changes that enable to work with `gr` are not released yet. You could install from source `pip install git+https://github.com/jbusecke/cmip6_preprocessing.git` to test those. You might have to uninstall the conda version for that. Thanks for your patience.

**Comment by DaisyShi19** [comment] 2020-03-04 19:33
It worked now for both 'gn and 'gr'. Now i'll close the issue and move forward. Cheers!

**Closed** 2020-03-04 19:33 UTC
